
#*********************************************************************
# SPx V1.92
# 11 Jan 2024 16:17:02: The following parameters were added
#*********************************************************************
ChannelDatabase.FirstChannelID = 1
ChannelDatabase.LastChannelID = 8
ChannelDatabaseChannel1.Type = 0x00000008
ChannelDatabaseChannel1.InputMedia = 0x00020000
ChannelDatabaseChannel1.OutputMedias = 0x00000000
ChannelDatabaseChannel1.FileID = 1
ChannelDatabaseChannel1.DisplayName = Tracks-hsb
ChannelDatabaseChannel1.LinkedChannelID = 0
ChannelDatabaseChannel1.LinkedChannelFlags = 0x00000000
ChannelDatabaseChannel1.InputEnabled = 1
ChannelDatabaseChannel1.OutputsEnabled = 0x00000000
ChannelDatabaseChannel1.IsLatLongSet = 1
ChannelDatabaseChannel1.LatitudeDegs = 31.349948
ChannelDatabaseChannel1.LongitudeDegs = 121.904502
ChannelDatabaseChannel1.SPxDecoderNetAddr = 239.192.77.78
ChannelDatabaseChannel1.SPxDecoderNetPort = 7778
ChannelDatabaseChannel1.SPxDecoderNetInterface = ""
ChannelDatabaseChannel1TrackDB.SenderID = 0
ChannelDatabaseChannel1TrackDB.PurgeInterval = -5
ChannelDatabaseChannel1TrackDB.PurgeIntervalPlots = -500
ChannelDatabaseChannel1TrackDB.PreserveTrailInterval = 0
ChannelDatabaseChannel1TrackDB.MinPreserveAgeSecs = 0.000
ChannelDatabaseChannel1TrackDB.PreserveIntervalSecs = 0.000
ChannelDatabaseChannel1TrackDB.UseLatLongForNavData = 1
ChannelDatabaseChannel1TrackDB.CalculateLatLongs = 1
ChannelDatabaseChannel2.Type = 0x00000008
ChannelDatabaseChannel2.InputMedia = 0x00020000
ChannelDatabaseChannel2.OutputMedias = 0x00000000
ChannelDatabaseChannel2.FileID = 2
ChannelDatabaseChannel2.DisplayName = Tracks-hsn
ChannelDatabaseChannel2.LinkedChannelID = 0
ChannelDatabaseChannel2.LinkedChannelFlags = 0x00000000
ChannelDatabaseChannel2.InputEnabled = 1
ChannelDatabaseChannel2.OutputsEnabled = 0x00000000
ChannelDatabaseChannel2.IsLatLongSet = 1
ChannelDatabaseChannel2.LatitudeDegs = 31.300350
ChannelDatabaseChannel2.LongitudeDegs = 121.847900
ChannelDatabaseChannel2.SPxDecoderNetAddr = 239.192.77.79
ChannelDatabaseChannel2.SPxDecoderNetPort = 7779
ChannelDatabaseChannel2.SPxDecoderNetInterface = ""
ChannelDatabaseChannel2TrackDB.SenderID = 0
ChannelDatabaseChannel2TrackDB.PurgeInterval = -5
ChannelDatabaseChannel2TrackDB.PurgeIntervalPlots = -500
ChannelDatabaseChannel2TrackDB.PreserveTrailInterval = 0
ChannelDatabaseChannel2TrackDB.MinPreserveAgeSecs = 0.000
ChannelDatabaseChannel2TrackDB.PreserveIntervalSecs = 0.000
ChannelDatabaseChannel2TrackDB.UseLatLongForNavData = 1
ChannelDatabaseChannel2TrackDB.CalculateLatLongs = 1
ChannelDatabaseChannel3.Type = 0x00000008
ChannelDatabaseChannel3.InputMedia = 0x00020000
ChannelDatabaseChannel3.OutputMedias = 0x00000000
ChannelDatabaseChannel3.FileID = 3
ChannelDatabaseChannel3.DisplayName = Tracks-ws
ChannelDatabaseChannel3.LinkedChannelID = 0
ChannelDatabaseChannel3.LinkedChannelFlags = 0x00000000
ChannelDatabaseChannel3.InputEnabled = 1
ChannelDatabaseChannel3.OutputsEnabled = 0x00000000
ChannelDatabaseChannel3.IsLatLongSet = 1
ChannelDatabaseChannel3.LatitudeDegs = 31.375167
ChannelDatabaseChannel3.LongitudeDegs = 121.496285
ChannelDatabaseChannel3.SPxDecoderNetAddr = 239.192.77.87
ChannelDatabaseChannel3.SPxDecoderNetPort = 7787
ChannelDatabaseChannel3.SPxDecoderNetInterface = ""
ChannelDatabaseChannel3TrackDB.SenderID = 0
ChannelDatabaseChannel3TrackDB.PurgeInterval = -5
ChannelDatabaseChannel3TrackDB.PurgeIntervalPlots = -500
ChannelDatabaseChannel3TrackDB.PreserveTrailInterval = 0
ChannelDatabaseChannel3TrackDB.MinPreserveAgeSecs = 0.000
ChannelDatabaseChannel3TrackDB.PreserveIntervalSecs = 0.000
ChannelDatabaseChannel3TrackDB.UseLatLongForNavData = 1
ChannelDatabaseChannel3TrackDB.CalculateLatLongs = 1
ChannelDatabaseChannel4.Type = 0x00000008
ChannelDatabaseChannel4.InputMedia = 0x00020000
ChannelDatabaseChannel4.OutputMedias = 0x00000000
ChannelDatabaseChannel4.FileID = 4
ChannelDatabaseChannel4.DisplayName = Tracks-ys
ChannelDatabaseChannel4.LinkedChannelID = 0
ChannelDatabaseChannel4.LinkedChannelFlags = 0x00000000
ChannelDatabaseChannel4.InputEnabled = 1
ChannelDatabaseChannel4.OutputsEnabled = 0x00000000
ChannelDatabaseChannel4.IsLatLongSet = 1
ChannelDatabaseChannel4.LatitudeDegs = 30.634521
ChannelDatabaseChannel4.LongitudeDegs = 122.057579
ChannelDatabaseChannel4.SPxDecoderNetAddr = 239.192.77.88
ChannelDatabaseChannel4.SPxDecoderNetPort = 7789
ChannelDatabaseChannel4.SPxDecoderNetInterface = ""
ChannelDatabaseChannel4TrackDB.SenderID = 0
ChannelDatabaseChannel4TrackDB.PurgeInterval = -5
ChannelDatabaseChannel4TrackDB.PurgeIntervalPlots = -500
ChannelDatabaseChannel4TrackDB.PreserveTrailInterval = 0
ChannelDatabaseChannel4TrackDB.MinPreserveAgeSecs = 0.000
ChannelDatabaseChannel4TrackDB.PreserveIntervalSecs = 0.000
ChannelDatabaseChannel4TrackDB.UseLatLongForNavData = 1
ChannelDatabaseChannel4TrackDB.CalculateLatLongs = 1
ChannelDatabaseChannel5.Type = 0x00000002
ChannelDatabaseChannel5.InputMedia = 0x00040000
ChannelDatabaseChannel5.OutputMedias = 0x00040000
ChannelDatabaseChannel5.FileID = 5
ChannelDatabaseChannel5.DisplayName = Radar-Hengshabei
ChannelDatabaseChannel5.LinkedChannelID = 0
ChannelDatabaseChannel5.LinkedChannelFlags = 0x00000000
ChannelDatabaseChannel5.InputEnabled = 1
ChannelDatabaseChannel5.OutputsEnabled = 0x00000000
ChannelDatabaseChannel5.IsLatLongSet = 1
ChannelDatabaseChannel5.LatitudeDegs = 31.349948
ChannelDatabaseChannel5.LongitudeDegs = 121.904502
ChannelDatabaseChannel5.OutputDeviceIndex = 0
ChannelDatabaseChannel5.NumSamples = 2048
ChannelDatabaseChannel5.NumAzimuths = 2048
ChannelDatabaseChannel5.MaxPrfChangeHz = 200.000
ChannelDatabaseChannel5.MaxPeriodChangeSecs = 1.000
ChannelDatabaseChannel5.TPGEnabled = 0
ChannelDatabaseChannel5.RGB = 0x00FF00
ChannelDatabaseChannel5Pim.RangeMode = 1
ChannelDatabaseChannel5Pim.AzimuthMode = 1
ChannelDatabaseChannel5Pim.ProcessingInterval = 1
ChannelDatabaseChannel5Pim.ProcessingMode = 0
ChannelDatabaseChannel5Pim.AziRefMode = 0
ChannelDatabaseChannel5Pim.Clear = 32
ChannelDatabaseChannel5Pim.Debug = 0
ChannelDatabaseChannel5Pim.Repeat = 10
ChannelDatabaseChannel5Pim.EnableFill = 1
ChannelDatabaseChannel5Pim.ConstantAziLimit = 0
ChannelDatabaseChannel5Pim.AzimuthOffset = 0.000
ChannelDatabaseChannel5Pim.IfLevel = 0
ChannelDatabaseChannel5Pim.CorrectPitchRoll = 1
ChannelDatabaseChannel5NetSend.Port = 20100
ChannelDatabaseChannel5NetSend.AddressString = 239.192.201.100
ChannelDatabaseChannel5NetSend.Interface = 192.168.0.89
ChannelDatabaseChannel5NetSend.Debug = 0x00000000
ChannelDatabaseChannel5NetSend.Format = 0
ChannelDatabaseChannel5NetSend.Source = 0
ChannelDatabaseChannel5NetSend.RangeFactor = 1
ChannelDatabaseChannel5NetSend.ReportClientDropout = 0
ChannelDatabaseChannel5NetSend.SndBufSize = 0
ChannelDatabaseChannel5NetSend.Enabled = 0
ChannelDatabaseChannel5NetSend.Mtu = 1400
ChannelDatabaseChannel5NetSend.TTL = -1
ChannelDatabaseChannel5NetSend.SAC = 0
ChannelDatabaseChannel5NetSend.SIC = 0
ChannelDatabaseChannel5NetSend.SummaryIntervalMsecs = 1000
ChannelDatabaseChannel5NetSend.SummaryText = "Cambridge Pixel SPx."
ChannelDatabaseChannel5NetSend.SummaryAlwaysEnabled = 0
ChannelDatabaseChannel5NetSend.AzimuthLimitDegs = 5.000
ChannelDatabaseChannel5NetSend.SkipBackJumpMaxDegs = 5.000
ChannelDatabaseChannel5NetSend.RangeResolution = 0
ChannelDatabaseChannel5NetSend.SPFEnabled = 0
ChannelDatabaseChannel5NetRecv.VideoCheckMsecs = 0
ChannelDatabaseChannel5NetRecv.VideoCheckThreshold = 0.000
ChannelDatabaseChannel5NetRecv.AddressString = 239.192.11.78
ChannelDatabaseChannel5NetRecv.Port = 1178
ChannelDatabaseChannel5NetRecv.DropoutThreshold = 2
ChannelDatabaseChannel5NetRecv.Interface = 192.168.0.89
ChannelDatabaseChannel5NetRecv.Debug = 0x00000000
ChannelDatabaseChannel5NetRecv.ExpectedSAC = 0
ChannelDatabaseChannel5NetRecv.ExpectedSIC = 0
ChannelDatabaseChannel5NetRecv.AziRefModeEnabled = 0
ChannelDatabaseChannel5NetRecv.NorthUp = 1
ChannelDatabaseChannel5NetRecv.AziInputRefMode = 0
ChannelDatabaseChannel5NetRecv.SPFEnabled = 1
ChannelDatabaseChannel5NetRecv.RangeIntervalMsecs = 1000
ChannelDatabaseChannel5NetRecv.DopplerFormat = 0
ChannelDatabaseChannel5GainOffsetProcess.Enabled = 1
ChannelDatabaseChannel5GainOffsetProcess.Gain = 1.000
ChannelDatabaseChannel5GainOffsetProcess.Offset = 0
ChannelDatabaseChannel5GainOffsetProcess.LocalRegion = ""
ChannelDatabaseChannel5GainOffsetProcess.LocalGain = 1.000
ChannelDatabaseChannel5GainOffsetProcess.LocalOffset = 0
ChannelDatabaseChannel6.Type = 0x00000002
ChannelDatabaseChannel6.InputMedia = 0x00040000
ChannelDatabaseChannel6.OutputMedias = 0x00040000
ChannelDatabaseChannel6.FileID = 6
ChannelDatabaseChannel6.DisplayName = Radar-Hengshanan
ChannelDatabaseChannel6.LinkedChannelID = 0
ChannelDatabaseChannel6.LinkedChannelFlags = 0x00000000
ChannelDatabaseChannel6.InputEnabled = 1
ChannelDatabaseChannel6.OutputsEnabled = 0x00000000
ChannelDatabaseChannel6.IsLatLongSet = 1
ChannelDatabaseChannel6.LatitudeDegs = 31.300350
ChannelDatabaseChannel6.LongitudeDegs = 121.847900
ChannelDatabaseChannel6.OutputDeviceIndex = 0
ChannelDatabaseChannel6.NumSamples = 2048
ChannelDatabaseChannel6.NumAzimuths = 2048
ChannelDatabaseChannel6.MaxPrfChangeHz = 200.000
ChannelDatabaseChannel6.MaxPeriodChangeSecs = 1.000
ChannelDatabaseChannel6.TPGEnabled = 0
ChannelDatabaseChannel6.RGB = 0xF8A407
ChannelDatabaseChannel6Pim.RangeMode = 1
ChannelDatabaseChannel6Pim.AzimuthMode = 1
ChannelDatabaseChannel6Pim.ProcessingInterval = 1
ChannelDatabaseChannel6Pim.ProcessingMode = 0
ChannelDatabaseChannel6Pim.AziRefMode = 0
ChannelDatabaseChannel6Pim.Clear = 32
ChannelDatabaseChannel6Pim.Debug = 0
ChannelDatabaseChannel6Pim.Repeat = 10
ChannelDatabaseChannel6Pim.EnableFill = 1
ChannelDatabaseChannel6Pim.ConstantAziLimit = 0
ChannelDatabaseChannel6Pim.AzimuthOffset = 0.000
ChannelDatabaseChannel6Pim.IfLevel = 0
ChannelDatabaseChannel6Pim.CorrectPitchRoll = 1
ChannelDatabaseChannel6NetSend.Port = 20104
ChannelDatabaseChannel6NetSend.AddressString = 239.192.201.104
ChannelDatabaseChannel6NetSend.Interface = 192.168.0.89
ChannelDatabaseChannel6NetSend.Debug = 0x00000000
ChannelDatabaseChannel6NetSend.Format = 0
ChannelDatabaseChannel6NetSend.Source = 0
ChannelDatabaseChannel6NetSend.RangeFactor = 1
ChannelDatabaseChannel6NetSend.ReportClientDropout = 0
ChannelDatabaseChannel6NetSend.SndBufSize = 0
ChannelDatabaseChannel6NetSend.Enabled = 0
ChannelDatabaseChannel6NetSend.Mtu = 1400
ChannelDatabaseChannel6NetSend.TTL = -1
ChannelDatabaseChannel6NetSend.SAC = 0
ChannelDatabaseChannel6NetSend.SIC = 0
ChannelDatabaseChannel6NetSend.SummaryIntervalMsecs = 1000
ChannelDatabaseChannel6NetSend.SummaryText = "Cambridge Pixel SPx."
ChannelDatabaseChannel6NetSend.SummaryAlwaysEnabled = 0
ChannelDatabaseChannel6NetSend.AzimuthLimitDegs = 5.000
ChannelDatabaseChannel6NetSend.SkipBackJumpMaxDegs = 5.000
ChannelDatabaseChannel6NetSend.RangeResolution = 0
ChannelDatabaseChannel6NetSend.SPFEnabled = 0
ChannelDatabaseChannel6NetRecv.VideoCheckMsecs = 0
ChannelDatabaseChannel6NetRecv.VideoCheckThreshold = 0.000
ChannelDatabaseChannel6NetRecv.AddressString = 239.192.11.79
ChannelDatabaseChannel6NetRecv.Port = 1179
ChannelDatabaseChannel6NetRecv.DropoutThreshold = 2
ChannelDatabaseChannel6NetRecv.Interface = 192.168.0.89
ChannelDatabaseChannel6NetRecv.Debug = 0x00000000
ChannelDatabaseChannel6NetRecv.ExpectedSAC = 0
ChannelDatabaseChannel6NetRecv.ExpectedSIC = 0
ChannelDatabaseChannel6NetRecv.AziRefModeEnabled = 0
ChannelDatabaseChannel6NetRecv.NorthUp = 1
ChannelDatabaseChannel6NetRecv.AziInputRefMode = 0
ChannelDatabaseChannel6NetRecv.SPFEnabled = 1
ChannelDatabaseChannel6NetRecv.RangeIntervalMsecs = 1000
ChannelDatabaseChannel6NetRecv.DopplerFormat = 0
ChannelDatabaseChannel6GainOffsetProcess.Enabled = 1
ChannelDatabaseChannel6GainOffsetProcess.Gain = 1.000
ChannelDatabaseChannel6GainOffsetProcess.Offset = 0
ChannelDatabaseChannel6GainOffsetProcess.LocalRegion = ""
ChannelDatabaseChannel6GainOffsetProcess.LocalGain = 1.000
ChannelDatabaseChannel6GainOffsetProcess.LocalOffset = 0
ChannelDatabaseChannel7.Type = 0x00000002
ChannelDatabaseChannel7.InputMedia = 0x00040000
ChannelDatabaseChannel7.OutputMedias = 0x00040000
ChannelDatabaseChannel7.FileID = 7
ChannelDatabaseChannel7.DisplayName = Radar-Wusong
ChannelDatabaseChannel7.LinkedChannelID = 0
ChannelDatabaseChannel7.LinkedChannelFlags = 0x00000000
ChannelDatabaseChannel7.InputEnabled = 1
ChannelDatabaseChannel7.OutputsEnabled = 0x00000000
ChannelDatabaseChannel7.IsLatLongSet = 1
ChannelDatabaseChannel7.LatitudeDegs = 31.375167
ChannelDatabaseChannel7.LongitudeDegs = 121.496285
ChannelDatabaseChannel7.OutputDeviceIndex = 0
ChannelDatabaseChannel7.NumSamples = 2048
ChannelDatabaseChannel7.NumAzimuths = 2048
ChannelDatabaseChannel7.MaxPrfChangeHz = 200.000
ChannelDatabaseChannel7.MaxPeriodChangeSecs = 1.000
ChannelDatabaseChannel7.TPGEnabled = 0
ChannelDatabaseChannel7.RGB = 0xFF0000
ChannelDatabaseChannel7Pim.RangeMode = 1
ChannelDatabaseChannel7Pim.AzimuthMode = 1
ChannelDatabaseChannel7Pim.ProcessingInterval = 1
ChannelDatabaseChannel7Pim.ProcessingMode = 0
ChannelDatabaseChannel7Pim.AziRefMode = 0
ChannelDatabaseChannel7Pim.Clear = 32
ChannelDatabaseChannel7Pim.Debug = 0
ChannelDatabaseChannel7Pim.Repeat = 10
ChannelDatabaseChannel7Pim.EnableFill = 1
ChannelDatabaseChannel7Pim.ConstantAziLimit = 0
ChannelDatabaseChannel7Pim.AzimuthOffset = 0.000
ChannelDatabaseChannel7Pim.IfLevel = 0
ChannelDatabaseChannel7Pim.CorrectPitchRoll = 1
ChannelDatabaseChannel7NetSend.Port = 20108
ChannelDatabaseChannel7NetSend.AddressString = 239.192.201.108
ChannelDatabaseChannel7NetSend.Interface = 192.168.0.89
ChannelDatabaseChannel7NetSend.Debug = 0x00000000
ChannelDatabaseChannel7NetSend.Format = 0
ChannelDatabaseChannel7NetSend.Source = 0
ChannelDatabaseChannel7NetSend.RangeFactor = 1
ChannelDatabaseChannel7NetSend.ReportClientDropout = 0
ChannelDatabaseChannel7NetSend.SndBufSize = 0
ChannelDatabaseChannel7NetSend.Enabled = 0
ChannelDatabaseChannel7NetSend.Mtu = 1400
ChannelDatabaseChannel7NetSend.TTL = -1
ChannelDatabaseChannel7NetSend.SAC = 0
ChannelDatabaseChannel7NetSend.SIC = 0
ChannelDatabaseChannel7NetSend.SummaryIntervalMsecs = 1000
ChannelDatabaseChannel7NetSend.SummaryText = "Cambridge Pixel SPx."
ChannelDatabaseChannel7NetSend.SummaryAlwaysEnabled = 0
ChannelDatabaseChannel7NetSend.AzimuthLimitDegs = 5.000
ChannelDatabaseChannel7NetSend.SkipBackJumpMaxDegs = 5.000
ChannelDatabaseChannel7NetSend.RangeResolution = 0
ChannelDatabaseChannel7NetSend.SPFEnabled = 0
ChannelDatabaseChannel7NetRecv.VideoCheckMsecs = 0
ChannelDatabaseChannel7NetRecv.VideoCheckThreshold = 0.000
ChannelDatabaseChannel7NetRecv.AddressString = 239.192.11.80
ChannelDatabaseChannel7NetRecv.Port = 1180
ChannelDatabaseChannel7NetRecv.DropoutThreshold = 2
ChannelDatabaseChannel7NetRecv.Interface = 192.168.0.89
ChannelDatabaseChannel7NetRecv.Debug = 0x00000000
ChannelDatabaseChannel7NetRecv.ExpectedSAC = 0
ChannelDatabaseChannel7NetRecv.ExpectedSIC = 0
ChannelDatabaseChannel7NetRecv.AziRefModeEnabled = 0
ChannelDatabaseChannel7NetRecv.NorthUp = 1
ChannelDatabaseChannel7NetRecv.AziInputRefMode = 0
ChannelDatabaseChannel7NetRecv.SPFEnabled = 1
ChannelDatabaseChannel7NetRecv.RangeIntervalMsecs = 1000
ChannelDatabaseChannel7NetRecv.DopplerFormat = 0
ChannelDatabaseChannel7GainOffsetProcess.Enabled = 1
ChannelDatabaseChannel7GainOffsetProcess.Gain = 1.000
ChannelDatabaseChannel7GainOffsetProcess.Offset = 0
ChannelDatabaseChannel7GainOffsetProcess.LocalRegion = ""
ChannelDatabaseChannel7GainOffsetProcess.LocalGain = 1.000
ChannelDatabaseChannel7GainOffsetProcess.LocalOffset = 0
ChannelDatabaseChannel8.Type = 0x00000002
ChannelDatabaseChannel8.InputMedia = 0x00040000
ChannelDatabaseChannel8.OutputMedias = 0x00040000
ChannelDatabaseChannel8.FileID = 8
ChannelDatabaseChannel8.DisplayName = Radar-Yangshan
ChannelDatabaseChannel8.LinkedChannelID = 0
ChannelDatabaseChannel8.LinkedChannelFlags = 0x00000000
ChannelDatabaseChannel8.InputEnabled = 1
ChannelDatabaseChannel8.OutputsEnabled = 0x00000000
ChannelDatabaseChannel8.IsLatLongSet = 1
ChannelDatabaseChannel8.LatitudeDegs = 30.634521
ChannelDatabaseChannel8.LongitudeDegs = 122.057579
ChannelDatabaseChannel8.OutputDeviceIndex = 0
ChannelDatabaseChannel8.NumSamples = 2048
ChannelDatabaseChannel8.NumAzimuths = 2048
ChannelDatabaseChannel8.MaxPrfChangeHz = 200.000
ChannelDatabaseChannel8.MaxPeriodChangeSecs = 1.000
ChannelDatabaseChannel8.TPGEnabled = 0
ChannelDatabaseChannel8.RGB = 0x00FF00
ChannelDatabaseChannel8Pim.RangeMode = 1
ChannelDatabaseChannel8Pim.AzimuthMode = 1
ChannelDatabaseChannel8Pim.ProcessingInterval = 1
ChannelDatabaseChannel8Pim.ProcessingMode = 0
ChannelDatabaseChannel8Pim.AziRefMode = 0
ChannelDatabaseChannel8Pim.Clear = 32
ChannelDatabaseChannel8Pim.Debug = 0
ChannelDatabaseChannel8Pim.Repeat = 10
ChannelDatabaseChannel8Pim.EnableFill = 1
ChannelDatabaseChannel8Pim.ConstantAziLimit = 0
ChannelDatabaseChannel8Pim.AzimuthOffset = 0.000
ChannelDatabaseChannel8Pim.IfLevel = 0
ChannelDatabaseChannel8Pim.CorrectPitchRoll = 1
ChannelDatabaseChannel8NetSend.Port = 20112
ChannelDatabaseChannel8NetSend.AddressString = 239.192.201.112
ChannelDatabaseChannel8NetSend.Interface = 192.168.0.89
ChannelDatabaseChannel8NetSend.Debug = 0x00000000
ChannelDatabaseChannel8NetSend.Format = 0
ChannelDatabaseChannel8NetSend.Source = 0
ChannelDatabaseChannel8NetSend.RangeFactor = 1
ChannelDatabaseChannel8NetSend.ReportClientDropout = 0
ChannelDatabaseChannel8NetSend.SndBufSize = 0
ChannelDatabaseChannel8NetSend.Enabled = 0
ChannelDatabaseChannel8NetSend.Mtu = 1400
ChannelDatabaseChannel8NetSend.TTL = -1
ChannelDatabaseChannel8NetSend.SAC = 0
ChannelDatabaseChannel8NetSend.SIC = 0
ChannelDatabaseChannel8NetSend.SummaryIntervalMsecs = 1000
ChannelDatabaseChannel8NetSend.SummaryText = "Cambridge Pixel SPx."
ChannelDatabaseChannel8NetSend.SummaryAlwaysEnabled = 0
ChannelDatabaseChannel8NetSend.AzimuthLimitDegs = 5.000
ChannelDatabaseChannel8NetSend.SkipBackJumpMaxDegs = 5.000
ChannelDatabaseChannel8NetSend.RangeResolution = 0
ChannelDatabaseChannel8NetSend.SPFEnabled = 0
ChannelDatabaseChannel8NetRecv.VideoCheckMsecs = 0
ChannelDatabaseChannel8NetRecv.VideoCheckThreshold = 0.000
ChannelDatabaseChannel8NetRecv.AddressString = 239.192.11.81
ChannelDatabaseChannel8NetRecv.Port = 1181
ChannelDatabaseChannel8NetRecv.DropoutThreshold = 2
ChannelDatabaseChannel8NetRecv.Interface = 192.168.0.89
ChannelDatabaseChannel8NetRecv.Debug = 0x00000000
ChannelDatabaseChannel8NetRecv.ExpectedSAC = 0
ChannelDatabaseChannel8NetRecv.ExpectedSIC = 0
ChannelDatabaseChannel8NetRecv.AziRefModeEnabled = 0
ChannelDatabaseChannel8NetRecv.NorthUp = 1
ChannelDatabaseChannel8NetRecv.AziInputRefMode = 0
ChannelDatabaseChannel8NetRecv.SPFEnabled = 1
ChannelDatabaseChannel8NetRecv.RangeIntervalMsecs = 1000
ChannelDatabaseChannel8NetRecv.DopplerFormat = 0
ChannelDatabaseChannel8GainOffsetProcess.Enabled = 1
ChannelDatabaseChannel8GainOffsetProcess.Gain = 1.000
ChannelDatabaseChannel8GainOffsetProcess.Offset = 0
ChannelDatabaseChannel8GainOffsetProcess.LocalRegion = ""
ChannelDatabaseChannel8GainOffsetProcess.LocalGain = 1.000
ChannelDatabaseChannel8GainOffsetProcess.LocalOffset = 0